force-app/main/default/objects/Inbound_Integration_Router__mdt/Inbound_Integration_Router__mdt.object-meta.xml
<CustomObject>
    <label>Inbound Integration Router</label>
    <pluralLabel>Inbound Integration Routers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Inbound_Integration_Router__mdt/fields/Custom_API__c.field-meta.xml
<CustomField>
    <fullName>Custom_API__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Custom API</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inbound_Integration_Router__mdt/fields/Incoming_Path__c.field-meta.xml
<CustomField>
    <fullName>Incoming_Path__c</fullName>
    <label>Incoming Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Integration_Router__mdt/fields/Logging_enabled__c.field-meta.xml
<CustomField>
    <fullName>Logging_enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Logging enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inbound_Integration_Router__mdt/fields/Redirected_To__c.field-meta.xml
<CustomField>
    <fullName>Redirected_To__c</fullName>
    <label>Redirected To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Integration_Router__mdt/fields/Retry_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Retry_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retry Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomAPIUtil.cls
public with sharing class CustomAPIUtil {
    public static Inbound_Integration_Router__mdt getCustomMetadata(String integrationName){
        return [SELECT Custom_API_Handler__c,
                        Custom_API__c,
                        DeveloperName,
                        Id,
                        Incoming_Path__c,
                        Integration_Name__c,
                        Label,
                        Language,
                        Logging_enabled__c,
                        MasterLabel,
                        NamespacePrefix,
                        QualifiedApiName,
                        Redirected_To__c,
                        Retry_Enabled__c,
                        SystemModstamp FROM Inbound_Integration_Router__mdt
                        WHERE DeveloperName =:integrationName WITH SECURITY_ENFORCED
                        LIMIT 1];
    }
}