force-app/main/default/objects/UserRegistration__c/UserRegistration__c.object-meta.xml
<CustomObject>
    <label>UserRegistration</label>
    <nameField>
        <label>UserRegistration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserRegistration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserRegistration__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <externalId>true</externalId>
    <label>User Name</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RegistrationPage_CustControllerTest.cls
@isTest
public class RegistrationPage_CustControllerTest {
    
    @isTest
    public static void registeruser_success(){
        
        PageReference vfRegistrationPage = Page.vf_registration_page;
        Test.setCurrentPage(vfRegistrationPage);
        
        RegistrationPage_CustController controller = new RegistrationPage_CustController();
        
        
        UserRegistration__c userRegis = new UserRegistration__c();
        userRegis.User_Name__c = 'Danga';
        controller.userRegistration = userRegis;
        
        PageReference registrationComplete = controller.registerUser();
        
        System.assertEquals('/apex/registration_success', registrationComplete.getUrl());
        
        
        
        
    }
    @isTest
    public static void registeruser_failure(){
        
        PageReference vfRegistrationPage = Page.vf_registration_page;
        Test.setCurrentPage(vfRegistrationPage);
        
        RegistrationPage_CustController controller = new RegistrationPage_CustController();
        UserRegistration__c userRegis = new UserRegistration__c();
        controller.userRegistration = userRegis;
        
        
        try{
            PageReference registrationComplete = controller.registerUser();
        }catch(Exception e){
            System.assert(e.getMessage().contains('Attemt'));            
        }
        
    }
    
}