force-app/main/default/objects/email__c/email__c.object-meta.xml
<CustomObject>
    <label>email</label>
    <nameField>
        <label>email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserRegistration__c/UserRegistration__c.object-meta.xml
<CustomObject>
    <label>UserRegistration</label>
    <nameField>
        <label>UserRegistration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserRegistration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserRegistration__c/fields/Firstname__c.field-meta.xml
<CustomField>
    <fullName>Firstname__c</fullName>
    <label>Firstname</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/Lastname__c.field-meta.xml
<CustomField>
    <fullName>Lastname__c</fullName>
    <label>Lastname</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserRegistration__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <externalId>true</externalId>
    <label>User Name</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RegistrationDAOManager.cls
public class RegistrationDAOManager {
    
    public List<UserRegistration__c> getUserAvailableUser(String userName){
        return [SELECT Id FROM UserRegistration__c WHERE user_name__c =:userName] ;       
    }  
    public Integer getCountOfRegisteredUsers(){
        return [SELECT count() FROM UserRegistration__c];
    }
    public List<UserRegistration__c> getRegisteredUsers(){
        return [SELECT Firstname__c,LastName__C,createddate, Email__c  FROM UserRegistration__c];
    }
}